new single vm

diff --git a/gcp/scripts/gcp-cloud-init-multiOS.yaml.bak.yaml b/gcp/scripts/gcp-cloud-init-multiOS.yaml.bak.yaml
--- a/gcp/scripts/gcp-cloud-init-multiOS.yaml.bak.yaml
+++ b/gcp/scripts/gcp-cloud-init-multiOS.yaml.bak.yaml
@@ -1,19 +1,18 @@
 #cloud-config
 # vim: syntax=yaml
 #
-###=============================================================================###
-# Bootstrap setup for a dnf/yum or apt based Linux server
+# -------------------------------------------------------------------------------
+# Copyright 2025 Karl Vietmeier / KCV Consulting
+# SPDX-License-Identifier: Apache-2.0
 #
-# cloud-init docs:
-#   https://cloudinit.readthedocs.io/en/latest/index.html
-#
-###=============================================================================###
+# AWS-adapted cloud-init config for Ubuntu/Debian & RHEL/CentOS/Rocky EC2
+# Bootstraps instance, installs dev tools, compiles FIO, iPerf, DOOL, SockPerf, Elbencho,
+# sets up labuser, enables NTP via AWS default server, configures shell environment.
+# -------------------------------------------------------------------------------
 
-# Upgrade the instance on first boot
-package_update: true
-package_upgrade: true
+package_update:  false
+package_upgrade: false
 
-# Packages to install on first boot on both distros
 packages:
   - libtool
   - tmux
@@ -28,171 +27,172 @@ packages:
   - jq
   - pkg-config
 
+# Users
+users:
+  - name: labuser
+    gecos: Lab User
+    groups: sudo
+    shell: /bin/bash
+    sudo: ALL=(ALL) NOPASSWD:ALL
+    #ssh_authorized_keys:
+    #  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQ... karlv@linuxtools
+    #  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD... karl.vietmeier@Tandaloor
+
 write_files:
-  ###--- Setup script to install tools and compile software
+  # Compile/install tools
   - path: /tmp/compiletools.sh
     permissions: '0755'
     content: |
       #!/bin/bash
       exec > >(tee -a /tmp/compiletools-out.log) 2>&1
       echo "compiletools.sh started at $(date)" 
-      
-      # Check OS version and install required dependencies
-      # Need a bunch dev libraries for FIO, elbencho, etc.
-      
-      # Ubuntu/Deb?
-      if [ -f /etc/debian_version ]; then
-         apt-get update -y
-         DEBIAN_FRONTEND=noninteractive apt-get install -y \
-            build-essential \
-            debhelper \
-            libboost-dev \
-            libboost-program-options-dev \
-            libboost-system-dev \
-            libboost-thread-dev \
-            libssl-dev \
-            libncurses-dev \
-            libnuma-dev \
-            libaio-dev \
-            librdmacm1 \
-            bpfcc-tools \
-            man-db \
-            chrony \
-            dnsutils \
-            nfs-common \
-            cmake \
-            dkms \
-            autoconf
 
-      # RedHat, Centos, Rocky etc.
+      # Detect OS
+      if [ -f /etc/debian_version ]; then
+        apt-get update -y
+        chmod -x /etc/update-motd.d/*
+        DEBIAN_FRONTEND=noninteractive apt-get install -y \
+          build-essential \
+          debhelper \
+          libboost-dev \
+          libboost-program-options-dev \
+          libboost-system-dev \
+          libboost-thread-dev \
+          libssl-dev \
+          libncurses-dev \
+          libnuma-dev \
+          libaio-dev \
+          librdmacm1 \
+          bpfcc-tools \
+          man-db \
+          chrony \
+          dnsutils \
+          docker \
+          nfs-common \
+          cmake \
+          dkms \
+          autoconf \
+          libcurl4-openssl-dev \
+          uuid-dev \
+          zlib1g-dev
+        
+        #--- Disable unattended-upgrades / auto updates ---
+        echo 'APT::Periodic::Update-Package-Lists "0";' > /etc/apt/apt.conf.d/20auto-upgrades
+        echo 'APT::Periodic::Unattended-Upgrade "0";' >> /etc/apt/apt.conf.d/20auto-upgrades
+        systemctl stop unattended-upgrades || true
+        systemctl disable unattended-upgrades || true
+        systemctl stop apt-daily.timer apt-daily-upgrade.timer || true
+        systemctl disable apt-daily.timer apt-daily-upgrade.timer || true
+        systemctl mask apt-daily.service apt-daily-upgrade.service || true
+        
       elif [ -f /etc/redhat-release ]; then
-          dnf groupinstall -y "Development Tools"
-          dnf install -y \
-            epel-release \
-            numactl-devel \
-            libaio-devel \
-            boost-devel \
-            boost-program-options \
-            boost-system \
-            boost-thread \
-            ncurses-devel \
-            openssl-devel \
-            bcc-tools \
-            man-db \
-            chrony \
-            bind-utils \
-            nfs-utils \
-            cmake \
-            rdma-core
+        dnf groupinstall -y "Development Tools"
+        dnf install -y \
+          epel-release \
+          numactl-devel \
+          libaio-devel \
+          boost-devel \
+          boost-program-options \
+          boost-system \
+          boost-thread \
+          ncurses-devel \
+          openssl-devel \
+          docker \
+          bcc-tools \
+          man-db \
+          chrony \
+          bind-utils \
+          nfs-utils \
+          cmake \
+          rdma-core \
+          libcurl-devel \
+          libuuid-devel \
+          zlib \
+          zlib-devel \
+          libarchive
       fi
 
       cd /root
       mkdir -p .local/bin
       mkdir -p git && cd git
 
-      #!/bin/bash
       LOG_FILE="/tmp/cloud-init-out.txt"
 
-      # Function to log a message, including errors, but continue execution
       log_and_continue() {
         echo "$1" >> "$LOG_FILE"
         if [ $? -ne 0 ]; then
-            echo "Warning: $1 failed!" >> "$LOG_FILE"
+          echo "Warning: $1 failed!" >> "$LOG_FILE"
         fi
       }
 
       # DOOL
       git clone https://github.com/scottchiefbaker/dool.git
-      log_and_continue "Cloned DOOL repository"
       cd dool
-      log_and_continue "Changed to DOOL directory"
       ./install.py
-      log_and_continue "DOOL installation"
       cd ..
 
       # FIO
       git clone https://github.com/axboe/fio.git
-      log_and_continue "Cloned FIO repository"
       cd fio
-      log_and_continue "Changed to FIO directory"
       ./configure
-      log_and_continue "FIO configure"
       make
-      log_and_continue "FIO make"
       make install
-      log_and_continue "FIO install"
       cd ..
 
       # iPerf
       git clone https://github.com/esnet/iperf.git
-      log_and_continue "Cloned iPerf repository"
       cd iperf
-      log_and_continue "Changed to iPerf directory"
       ./configure
-      log_and_continue "iPerf configure"
       make
-      log_and_continue "iPerf make"
       make install
-      log_and_continue "iPerf install"
       cd ..
-      # Fix for missing libiperf.so.0 after build
       echo "/usr/local/lib" > /etc/ld.so.conf.d/iperf.conf && log_and_continue "Added /usr/local/lib to ld.so.conf.d"
-      ldconfig && log_and_continue "Ran ldconfig to refresh library links"
+      ldconfig && log_and_continue "Ran ldconfig"
 
       # SockPerf
       git clone https://github.com/mellanox/sockperf
-      log_and_continue "Cloned SockPerf repository"
       cd sockperf
-      log_and_continue "Changed to SockPerf directory"
       ./autogen.sh
-      log_and_continue "SockPerf autogen"
       ./configure
-      log_and_continue "SockPerf configure"
       make
-      log_and_continue "SockPerf make"
       make install
-      log_and_continue "SockPerf install"
       cd ..
 
-      # Elbencho
+      # Elbencho with S3 support
       git clone https://github.com/breuner/elbencho.git
-      log_and_continue "Cloned Elbencho repository"
       cd elbencho
-      log_and_continue "Changed to Elbencho directory"
-      make -j "$(nproc)"
-      log_and_continue "Elbencho make"
-
+      make S3_SUPPORT=1 -j "$(nproc)"
       if [ -f /etc/redhat-release ]; then
         make rpm && dnf install -y ./packaging/RPMS/x86_64/elbencho*.rpm
       elif [ -f /etc/debian_version ]; then
-        make install && log_and_continue "Elbencho installed manually on Debian-based system"
+        make install
       fi
-
       cd /root
 
-      # Setup labuser scripts and folders
+      # Setup labuser folders
       mkdir -p /home/labuser/output
       chown -R labuser:labuser /home/labuser/output
       cd /home/labuser
       git clone https://github.com/kvietmeier/scripts.git
       chown -R labuser:labuser /home/labuser/scripts
 
-
+      # Enable chrony
       if [ -f /etc/debian_version ]; then
-          systemctl enable chrony
-          systemctl restart chrony
+        systemctl enable chrony
+        systemctl restart chrony
       elif [ -f /etc/redhat-release ]; then
-          systemctl enable chronyd
-          systemctl restart chronyd
+        systemctl enable chronyd
+        systemctl restart chronyd
       fi
 
       echo "compiletools.sh completed at $(date)" >> /tmp/cloud-init-out.txt
 
-  ###--- Setup shell environment
+  # Labuser shell environment
   - path: /home/labuser/.bashrc
+    owner: labuser:labuser
+    append: true
+    defer: true
     content: |
-
-      # Added by cloud-init
       alias la="ls -Av"
       alias ls="ls -hF --color=auto"
       alias l="ls -CFv"
@@ -205,30 +205,14 @@ write_files:
       alias cdu='cd ..'
       alias df='df -kh'
       alias du='du -h'
-
-      ### History
-      # Append to the history file, don't overwrite it
-      shopt -s histappend
-
-      # Immediately save commands to history file after each command
-      PROMPT_COMMAND="history -a; history -n"
-
-      # Set a large number of history lines
-      export HISTSIZE=100000
-      export HISTFILESIZE=200000
-
       set -o vi
       bind 'set bell-style none'
 
-    owner: labuser:labuser
-    append: true
-    defer: true
-
+  # Root shell environment
   - path: /root/.bashrc
+    owner: root:root
+    append: true
     content: |
-
-      ####
-      # Added by cloud-init
       alias ls="ls -hFv --color=auto"
       alias l="ls -CFv"
       alias la="ls -Av"
@@ -241,23 +225,8 @@ write_files:
       alias cdu='cd ..'
       alias df='df -kh'
       alias du='du -h'
-
-      ### History
-      # Append to the history file, don't overwrite it
-      shopt -s histappend
-
-      # Immediately save commands to history file after each command
-      PROMPT_COMMAND="history -a; history -n"
-
-      # Set a large number of history lines
-      export HISTSIZE=100000
-      export HISTFILESIZE=200000
-
       set -o vi
       bind 'set bell-style none'
-
-    owner: root:root
-    append: true
 
   ###--- Setup time keeping
   - path: /etc/chrony/chrony.conf
@@ -271,27 +240,12 @@ write_files:
       bindcmdaddress 127.0.0.1
       bindcmdaddress ::1
 
-  ###--- Flag file
+  # Flag file
   - path: /root/CONFIGURED_BY_CLOUD_INIT
 
 runcmd:
-  - curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
-  - bash add-google-cloud-ops-agent-repo.sh --also-install
   - systemctl restart google-cloud-ops-agent
   - bash /tmp/compiletools.sh
+  - echo "cloud-init completed successfully at $(date)" > /tmp/cloud-init-completed.txt
 
-###--- Users - Leave here for now
-#      Need to add your keys - will populate .ssh/authorized_keys
-users:
-  - name: labuser
-    gecos: Lab User
-    groups: sudo
-    shell: /bin/bash
-    sudo: ALL=(ALL) NOPASSWD:ALL
-    ssh_authorized_keys:
-      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDj/oqU+Kjs/sLN67JZ798S42efzK/jBKE3RWj4n9SJR6FYaijoy46qXWoC26ibOKhsO01g4OPeZAoUJq39hwsWNw/bTFKsjBuO6jRaNroybK2/lzQuX2oku0pclreXjPy/x0Mrf9ZD6Jzm0sbr9bk52KUdy6cPjFBIvVUNGXRLFm6AKggqWDzY3+9ONLyAihginw9N+yF28bQYjUwUbuy4k9gkD+cTWKNl1Al58rOAuifAJDMAA7CrlsNXK3nf4VtaURh4n3CbOoJI+auRiPfO4EoJGYVYVFy6V2NeSDV52q+7SUXXclb6c6DEVxLu2YAe9sMmUkL/N62uKAxrOqX+qJHXdOm/TOcHB+tw/jTDafRSJcPZ+EuGw4FjROEtEAMHus2poHN0qF0vdTm0DuNWHtH+ABpCHP8rvQeybkR3yFjStTyJlTLPTnY0/8gt8ykLWFyYtZott+hszXe6NM8lQlK9BiRi6e3F+LRBr1fMpQtOV0gemhaqYwCRdZKckqM= karlv@linuxtools
-      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOVhK8T5vJgKqXzSgDryh1EQEReE1lU9CvlBK8v4bG+eTjhPqacXqPkUWPlnM+kA1l3xe/GBxbIeoJ/WruUZV58SBjUUEMYN0qyKVwl+G5GqhijGAsWNC1KsfpTHNRRplZWAkKajAzb57kCzdNvFmOi86ENhn4gYFTWqAPEYALMnq6T1D52SELJGs/A3fwDEE99nTjcZ4/Huv1z+WWJmZEkSRWNtYLD/mx+cP41UHKCEIgsffvKH3o/IHgpsDGi5sQ8AKHChNkHb3vWQVPHx1BZDwxEUG7SPjY4gc/wRtrdauzMvdKvm9AUi1paY2PCGViLcysv619hQj02k/OQBJBy7MqplB1waoisxDuxKMSKjeKTyMGbMfv+MCrQd1iT+qdQtQImvyxRtQnYnbNMjnLPYUey7/kTkb4Xggm/hhuJOxnFqH/9WILDb81I4jElis+raXh0Vnt7gQ7OAO74osiLqD7uGuhytRCLqnU5VQmEAGdpxahxtirRu0eVQr/Ncs= karl.vietmeier@Tandaloor
-
-timezone: "America/Los_Angeles"
-
-final_message: Post creation OS config done
+final_message: "========= Post Install cloud-init Completed ========="
